package Jframes;

import clases.Conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paueguibar
 */
public class EditarCuenta extends javax.swing.JFrame {
    Conectar conn;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form AgregarCuenta
     */
    public EditarCuenta() {
        initComponents();
        conn = new Conectar();
        loadPaciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEC = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMat = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelarEC = new javax.swing.JButton();
        txtNombre = new javax.swing.JComboBox<>();
        btnOK = new javax.swing.JButton();
        txtCant = new javax.swing.JTextField();
        txtprecioU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnMostrarC = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Paciente:");

        jLabel8.setFont(new java.awt.Font("Songti TC", 0, 36)); // NOI18N
        jLabel8.setText("Editar Cuenta");

        tableEC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Cantidad", "Materiales", "Precio Unitario", "Subtotal", "I.V.A."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableECMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEC);

        jLabel2.setText("Cantidad");

        jLabel3.setText("Materiales");

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelarEC.setText("Cancelar");
        btnCancelarEC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarECActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio Unitario");

        jLabel5.setText("Subtotal");

        jLabel6.setText("I.V.A");

        jLabel7.setText("id:");

        btnMostrarC.setText("Mostrar Cuenta");
        btnMostrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 362, Short.MAX_VALUE)
                .addComponent(btnMostrarC)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtIva, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMat, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCant, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtprecioU, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtSub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarEC)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnOK)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btnMostrarC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtprecioU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarEC)
                            .addComponent(btnActualizar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // when button OK is clicked itll get the patient and display its cuenta
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        //display patient's bill
        createTable();
    }//GEN-LAST:event_btnOKActionPerformed
    
    //this method will display the row selected on the right when clicked
    private void tableECMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableECMouseClicked
        // TODO add your handling code here:
        //select item to edit
        DefaultTableModel df = (DefaultTableModel)tableEC.getModel();
        int SelectIndex = tableEC.getSelectedRow();
        lblId.setText(df.getValueAt(SelectIndex, 0).toString());
        txtCant.setText(df.getValueAt(SelectIndex,1 ).toString());
        txtMat.setText(df.getValueAt(SelectIndex,2).toString());
        txtprecioU.setText(df.getValueAt(SelectIndex,3 ).toString());
        txtSub.setText(df.getValueAt(SelectIndex,4 ).toString());
        txtIva.setText(df.getValueAt(SelectIndex,5 ).toString());
        
    }//GEN-LAST:event_tableECMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
            //read input to updtate
            String paciente = txtNombre.getSelectedItem().toString();
            String cant = txtCant.getText();
            String mat = txtMat.getText();
            String precioU = txtprecioU.getText();
            String sub = txtSub.getText();
            String iva = txtIva.getText();  
            String id = lblId.getText();
           
            //make the updates 
            pst = conn.getConnection().prepareStatement("update cuentas set material = ?, cantidad = ?, precio = ?, subtotal = ?, precioIva = ? where id = ?");
            pst.setString(1,mat);
            pst.setDouble(2, Double.parseDouble(cant));
            pst.setDouble(3, convertToNo(precioU));
            pst.setDouble(4, convertToNo(sub));
            pst.setDouble(5, convertToNo(iva));      
            pst.setInt(6,Integer.parseInt(id));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Cuenta Actualizada");
        } catch(SQLException e) {
            Logger.getLogger(EditarCuenta.class.getName()).log(Level.SEVERE, null, e);
            JOptionPane.showMessageDialog(this,"Cuenta NO Actualizada, intente de nuevo");
        }
        updateSubtotal();
        updateIva();
        updateCuentaReal();       
        createTable();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCancelarECActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarECActionPerformed
        // TODO add your handling code here:
        PagPrincipalRecep ppr = new PagPrincipalRecep();
        this.dispose();
        ppr.setVisible(true);
    }//GEN-LAST:event_btnCancelarECActionPerformed

    private void btnMostrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MostrarCuenta mc = new MostrarCuenta();
        mc.setVisible(true);
    }//GEN-LAST:event_btnMostrarCActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // get id 
        int id = Integer.parseInt(lblId.getText());
        try {
            //delete item that matches that id
            pst = conn.getConnection().prepareStatement("delete from `cuentas` WHERE `id`= ?");
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Material Eliminado Exitosamente");
            
            //generate updated table
            createTable();
            
            //update cuentas
            updateSubtotal();
            updateIva();
            updateCuentaReal();
            
        } catch (SQLException ex) {
            Logger.getLogger(EditarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    //load pacientes actuales
    public void loadPaciente() {
        try {
            pst = conn.getConnection().prepareStatement("SELECT `nombre` FROM `Paciente` WHERE `egreso` IS NULL");
            rs = pst.executeQuery();
            txtNombre.removeAll(); 
            
            while(rs.next()) {
                txtNombre.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EditarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //remove "$" from number to add it to DB
    public double convertToNo(String valueString) {
        String trimmedString = valueString.replace("$", "");
        trimmedString = trimmedString.trim();
        double value = Double.parseDouble(trimmedString); 
        return value;
    }
    
    public void updateCuentaReal() {
        String paciente = txtNombre.getSelectedItem().toString();
        // this try and catch will update the cuenta real of the pacient after adding something to the individual bill
        // by adding all precio + iva
        try {
            pst = conn.getConnection().prepareStatement("UPDATE `Paciente` SET `Paciente`.`cuenta real` = (SELECT SUM(`cuentas`.`precioIva`) FROM `cuentas` WHERE `cuentas`.`paciente` = ?) WHERE `Paciente`.`nombre` = ?");
            pst.setString(1, paciente);
            pst.setString(2,paciente);
            pst.executeUpdate();
     
        } catch (SQLException ex) {
            Logger.getLogger(EditarCuenta.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }
    
    //display the bill
    public void createTable() {
        String paciente = txtNombre.getSelectedItem().toString();
        
         try {
            pst = conn.getConnection().prepareStatement("SELECT `id`,`cantidad`,`material`,`precio`, `subtotal`,`precioIva` FROM `cuentas` WHERE `paciente` = ?");
            pst.setString(1, paciente);
            rs = pst.executeQuery();
            ResultSetMetaData Rsm = rs.getMetaData();
            int c;
            c = Rsm.getColumnCount();            
            DefaultTableModel df = (DefaultTableModel)tableEC.getModel();
            df.setRowCount(0);                    
            while (rs.next()) {
                Vector v2 = new Vector();
                for(int i = 1; i <= c; i++) {
                    v2.add(rs.getString("id"));
                    v2.add(rs.getString("cantidad"));
                    v2.add(rs.getString("material"));
                    v2.add("$" + rs.getString("precio"));
                    v2.add("$" + rs.getString("subtotal"));
                    v2.add("$" + rs.getString("precioIva"));
          
                }
                        
                df.addRow(v2);
                                                         
            }
            

         } catch (SQLException ex) {
            Logger.getLogger(Historial.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    
    // update subtotal to multiply the new number of materials
    public void updateSubtotal() {
        try {
                pst = conn.getConnection().prepareStatement("UPDATE `cuentas` SET `cuentas`.`subtotal` = `cuentas`.`precio` * `cuentas`.`cantidad`");
                pst.executeUpdate();
            
            } catch (SQLException ex) {
                Logger.getLogger(CuentaHosp.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    //update iva by multiplying subtotal * 1.16 if its not med or sol
    public void updateIva() {
        try {
                
                pst = conn.getConnection().prepareStatement("UPDATE `cuentas` SET `cuentas`.`precioIva` = `cuentas`.`subtotal` * 1.16 where `cuentas`.`iva` = 'Y' ");
                pst.executeUpdate();
                pst = conn.getConnection().prepareStatement("UPDATE `cuentas` SET `cuentas`.`precioIva` = `cuentas`.`subtotal` where `cuentas`.`iva` = 'N' ");
                pst.executeUpdate();
                
            
            } catch (SQLException ex) {
                Logger.getLogger(CuentaHosp.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    
    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelarEC;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMostrarC;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblId;
    private javax.swing.JTable tableEC;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtMat;
    private javax.swing.JComboBox<String> txtNombre;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtprecioU;
    // End of variables declaration//GEN-END:variables
}
