package Jframes;

import clases.Conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author paueguibar
 */
public class EgresarPaciente extends javax.swing.JFrame {
    Conectar conn;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form EditarPaciente
     */
    public EgresarPaciente() {
        initComponents();
        conn = new Conectar();
        setDate();
        loadPacienteActuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtFechaEgreso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAceptarEP = new javax.swing.JButton();
        btnCancelarEP = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        boxNombre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtDiag = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFact = new javax.swing.JTextField();
        txtRecibo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCenso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblEstatus = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        jLabel7.setText("Recibo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del Paciente");

        jLabel2.setText("Fecha de Egreso");

        btnAceptarEP.setText("Aceptar");
        btnAceptarEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEPActionPerformed(evt);
            }
        });

        btnCancelarEP.setText("Cancelar");
        btnCancelarEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEPActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Songti TC", 0, 36)); // NOI18N
        jLabel8.setText("Egresar Paciente");

        jLabel3.setText("Diagnóstico Egreso:");

        jLabel6.setText("Factura:");

        txtFact.setText("-");

        txtRecibo.setText("-");

        jLabel4.setText("Recibo:");

        btnCenso.setText("Censo");
        btnCenso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCensoActionPerformed(evt);
            }
        });

        jLabel5.setText("Estatus");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnCenso)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addComponent(jLabel5))
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiag)
                    .addComponent(txtFechaEgreso)
                    .addComponent(txtFact)
                    .addComponent(txtRecibo, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblEstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnAceptarEP)
                .addGap(76, 76, 76)
                .addComponent(btnCancelarEP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btnCenso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtFechaEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtDiag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarEP)
                    .addComponent(btnCancelarEP))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEPActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PagPrincipalRecep ppr = new PagPrincipalRecep();
        ppr.setVisible(true);
    }//GEN-LAST:event_btnCancelarEPActionPerformed

    private void btnAceptarEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEPActionPerformed
        // TODO add your handling code here:
        
        //read inputs
        String paciente = boxNombre.getSelectedItem().toString();
        String diag = txtDiag.getText();
        String egreso = txtFechaEgreso.getText();
        String fact = txtFact.getText();
        String recibo = txtRecibo.getText();
        try {
            // add fecha egreso, diagnostico egreso and estatus of egresado
            pst = conn.getConnection().prepareStatement("UPDATE `Paciente` SET `egreso` = ?, `diagnosticoEgreso` = ?, `estatus` = ? WHERE `nombre` = ?");
            pst.setString(1, egreso);
            pst.setString(2, diag);
            pst.setString(3, "egresado");
            pst.setString(4, paciente);
            pst.executeUpdate(); 

            //if fact != null, add it to the paciente 
            if(!fact.equals("-")) {
                pst = conn.getConnection().prepareStatement("select facturas from Paciente where nombre = ?");
                pst.setString(1, paciente);
                rs = pst.executeQuery();
                if(rs.next()) {
                    String res = rs.getString("facturas");
                    if(res == null) {
                        pst = conn.getConnection().prepareStatement("update Paciente set facturas = ? where nombre = ?");
                        pst.setString(1, fact);
                        pst.setString(2, paciente);
                        pst.executeUpdate();
                    } else {
                        pst = conn.getConnection().prepareStatement("update Paciente set facturas = CONCAT(facturas, ' ',?) where nombre = ?");
                        pst.setString(1, fact);
                        pst.setString(2, paciente);
                        pst.executeUpdate();
                    }
                }       
            }  
            
            //if recibo != null, add it to the paciente 
            if(!recibo.equals("-")) {
                pst = conn.getConnection().prepareStatement("select recibo from Paciente where nombre = ?");
                pst.setString(1, paciente);
                rs = pst.executeQuery();
                if(rs.next()) {
                    String res = rs.getString("recibo");
                    if(res == null) {
                        pst = conn.getConnection().prepareStatement("update Paciente set recibo = ? where nombre = ?");
                        pst.setString(1, recibo);
                        pst.setString(2, paciente);
                        pst.executeUpdate();
                    } else {
                        pst = conn.getConnection().prepareStatement("update Paciente set recibo = CONCAT(recibo, ' ',?) where nombre = ?");
                        pst.setString(1, recibo);
                        pst.setString(2, paciente);
                        pst.executeUpdate();
                    }
                }       
            } 
                       
            JOptionPane.showMessageDialog(this, "Paciente egresado exitosamente");
            
        } catch (SQLException ex) {
            Logger.getLogger(EgresarPaciente.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Paciente NO egresado, intente de nuevo");

        }
        
        
        //recet parameters
        boxNombre.setSelectedIndex(-1);
        txtDiag.setText("");
        txtRecibo.setText("");
        txtFact.setText("");
        boxNombre.removeAllItems();
        loadPacienteActuales();
        
    }//GEN-LAST:event_btnAceptarEPActionPerformed

    private void btnCensoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCensoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        CensoPacientes cp =new CensoPacientes();
        cp.setVisible(true);
    }//GEN-LAST:event_btnCensoActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        try {
            // TODO add your handling code here:
            String nombre = boxNombre.getSelectedItem().toString();
            pst = conn.getConnection().prepareStatement("SELECT `estatus` FROM `Paciente` WHERE `nombre` = ?");
            pst.setString(1, nombre);
            rs = pst.executeQuery(); 
            boxNombre.removeAll();
            
            while(rs.next()) {
                lblEstatus.setText(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(EgresarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnOKActionPerformed
    //set todays date automatically
    public void setDate() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        // Get today's date
        LocalDate currentDate = LocalDate.now();

        // Format the date as a string
        String formattedDate = currentDate.format(formatter);

        
        txtFechaEgreso.setText(formattedDate);
    }
    
    //loads active patients 
    public void loadPacienteActuales() {
        try {
            pst = conn.getConnection().prepareStatement("SELECT `nombre` FROM `Paciente`");
            rs = pst.executeQuery();
            boxNombre.removeAll(); 
            
            while(rs.next()) {
                boxNombre.addItem(rs.getString(1));
            }
                       
            
        } catch (SQLException ex) {
            Logger.getLogger(EgresarPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EgresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EgresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EgresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EgresarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EgresarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxNombre;
    private javax.swing.JButton btnAceptarEP;
    private javax.swing.JButton btnCancelarEP;
    private javax.swing.JButton btnCenso;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JTextField txtDiag;
    private javax.swing.JTextField txtFact;
    private javax.swing.JTextField txtFechaEgreso;
    private javax.swing.JTextField txtRecibo;
    // End of variables declaration//GEN-END:variables
}
