package Jframes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import clases.Conectar;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author paueguibar
 */
public class Pago extends javax.swing.JFrame {
    
    Conectar conn;
    PreparedStatement pst;
    ResultSet rs;

    /**
     * Creates new form CorteCaja
     */
    public Pago() {
        initComponents();
        conn = new Conectar();
        loadPacienteActuales();
        setDate();
        unSetPaq();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtNombre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        boxPago = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePago = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        btnPaquete = new javax.swing.JToggleButton();
        lblPaq = new javax.swing.JLabel();
        lblDif = new javax.swing.JLabel();
        txtPaq = new javax.swing.JTextField();
        txtDif = new javax.swing.JTextField();
        btnOKPaq = new javax.swing.JButton();
        btnAMostrarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Cuenta Real");

        lblTot.setText("$");

        jLabel1.setText("Nombre del Paciente");

        jLabel8.setFont(new java.awt.Font("Songti TC", 0, 36)); // NOI18N
        jLabel8.setText("Nuevo Pago");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo de Pago: ");

        boxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo ", "Tarjeta Débito", "Tarjeta Crédito" }));
        boxPago.setSelectedIndex(-1);

        jLabel5.setText("Cantidad");

        jLabel9.setFont(new java.awt.Font("Songti TC", 0, 24)); // NOI18N
        jLabel9.setText("Pagos:");

        tablePago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fecha", "Monto", "Tipo de Pago"
            }
        ));
        jScrollPane3.setViewportView(tablePago);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        btnPaquete.setText("Paquete");
        btnPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteActionPerformed(evt);
            }
        });

        lblPaq.setText("Paquete");

        lblDif.setText("Diferencia");

        btnOKPaq.setText("OK");
        btnOKPaq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKPaqActionPerformed(evt);
            }
        });

        btnAMostrarC.setText("Mostrar Cuenta");
        btnAMostrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMostrarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxPago, 0, 130, Short.MAX_VALUE)
                                    .addComponent(txtCant)
                                    .addComponent(btnAgregar)
                                    .addComponent(txtFecha)))
                            .addComponent(btnPaquete))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDif)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDif, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblTot, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblPaq)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtPaq))))
                                .addGap(258, 258, 258)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOK)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(166, 166, 166)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAMostrarC)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOKPaq)
                .addGap(348, 348, 348))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAMostrarC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblTot))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaq)
                            .addComponent(btnPaquete)
                            .addComponent(txtPaq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDif)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(boxPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100)
                        .addComponent(btnAgregar)))
                .addGap(34, 34, 34)
                .addComponent(btnOKPaq)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PagPrincipalRecep ppr = new PagPrincipalRecep();
        ppr.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed
    
    /* get the amount paid and insert it to DB pagos 
    update cuenta real
    display the new payment
    */
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            // TODO add your handling code here:
            //read inputs
            String fecha = txtFecha.getText();
            String paciente = txtNombre.getSelectedItem().toString();
            String tipo = boxPago.getSelectedItem().toString();
            double monto = Double.parseDouble(txtCant.getText());
            
            //instert into pagos DB
            pst = conn.getConnection().prepareStatement("insert into pagos(paciente,monto,tipo,fecha)values(?,?,?,?)");
            pst.setString(1, paciente);
            pst.setDouble(2, monto);
            pst.setString(3, tipo);
            pst.setString(4, fecha);
            pst.executeUpdate();
            
            
            // output success
            JOptionPane.showMessageDialog(this,"Pago Agregado");
            
            //update cuenta real
            pst = conn.getConnection().prepareStatement("UPDATE `Paciente` SET `Paciente`.`cuenta real` = `Paciente`.`cuenta real` - ?  WHERE `Paciente`.`nombre` = ?");
            pst.setDouble(1, monto);
            pst.setString(2,paciente);
            pst.executeUpdate();
     
                  
        } catch (SQLException ex) {
            Logger.getLogger(Pago.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Pago NO Agregado, intente de nuevo");
        }
        
        //method
        displayPago();
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        displayPago();
        unSetPaq();
        
    }//GEN-LAST:event_btnOKActionPerformed
    
    // add paquete
    private void btnPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteActionPerformed
        // TODO add your handling code here:
        lblDif.setVisible(true);
        lblPaq.setVisible(true);
        txtDif.setVisible(true);
        txtPaq.setVisible(true);
        btnOKPaq.setVisible(true);
    }//GEN-LAST:event_btnPaqueteActionPerformed

    private void btnOKPaqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKPaqActionPerformed
        // TODO add your handling code here:
        //read inputs of paquete
        Double paq = Double.valueOf(txtPaq.getText());
        String paciente = txtNombre.getSelectedItem().toString();
        try {
            //update paquete
            pst = conn.getConnection().prepareStatement("update Paciente set paquete = ? where nombre = ?");
            pst.setDouble(1, paq);
            pst.setString(2, paciente);
            pst.executeUpdate();
            
            //update diferencia
            pst = conn.getConnection().prepareStatement("update Paciente set diferencia = `cuenta real` - `paquete` where nombre = ?");
            pst.setString(1, paciente);
            pst.executeUpdate();
            
            // display diferencia
            pst = conn.getConnection().prepareStatement("SELECT `diferencia` FROM `Paciente` WHERE `nombre` = ?");
            pst.setString(1,paciente);
            rs = pst.executeQuery();   
            if (rs.next()) {
                txtDif.setText("$"+rs.getString("diferencia"));
            }
            JOptionPane.showMessageDialog(this,"Paquete Agregado");
            
        } catch (SQLException ex) {
            Logger.getLogger(Pago.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Paquete NO Agregado, intente de nuevo");
        }
        
        
        
        
    }//GEN-LAST:event_btnOKPaqActionPerformed

    private void btnAMostrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMostrarCActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MostrarCuenta mc = new MostrarCuenta();
        mc.setVisible(true);
        
    }//GEN-LAST:event_btnAMostrarCActionPerformed
    
// hide paquete
    public void unSetPaq() {
        lblDif.setVisible(false);
        lblPaq.setVisible(false);
        txtDif.setVisible(false);
        txtPaq.setVisible(false);
        btnOKPaq.setVisible(false);
        btnPaquete.setSelected(false);
        txtPaq.setText("");
        txtDif.setText("");
        
    }
    //This method calls all the pacientes that are active (that have no fecha egraso) to display it in the combobox so they
    //mostrar the cuenta
    public void loadPacienteActuales() {
        try {
            pst = conn.getConnection().prepareStatement("SELECT `nombre` FROM `Paciente` WHERE `egreso` IS NULL");
            rs = pst.executeQuery();
            txtNombre.removeAll(); 
            
            while(rs.next()) {
                txtNombre.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Pago.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // display the payments in the table and the cuenta real
    public void displayPago() {
        
        String paciente = txtNombre.getSelectedItem().toString();

        try {
            pst = conn.getConnection().prepareStatement("SELECT `fecha`,`monto`,`tipo` FROM `pagos` WHERE `paciente` = ?");
            pst.setString(1, paciente);
            rs = pst.executeQuery();
            ResultSetMetaData Rsm = rs.getMetaData();
            int c;
            c = Rsm.getColumnCount();
            DefaultTableModel df = (DefaultTableModel)tablePago.getModel();
            df.setRowCount(0);
            while (rs.next()) {
                Vector v2 = new Vector();
                for(int i = 1; i <= c; i++) {
                    v2.add(rs.getString("fecha"));
                    v2.add("$" + rs.getString("monto"));
                    v2.add(rs.getString("tipo"));     
                }

                df.addRow(v2);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Pago.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DecimalFormat decimalFormat = new DecimalFormat("#.##"); 
        try {
            pst = conn.getConnection().prepareStatement("SELECT `cuenta real` FROM `Paciente` WHERE `nombre` = ?");
            pst.setString(1,paciente);
            rs = pst.executeQuery();   
            while (rs.next()) {
                lblTot.setText("$"+rs.getString("cuenta real"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(MostrarCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void setDate() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        // Get today's date
        LocalDate currentDate = LocalDate.now();

        // Format the date as a string
        String formattedDate = currentDate.format(formatter);

        
        txtFecha.setText(formattedDate);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPago;
    private javax.swing.JButton btnAMostrarC;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOKPaq;
    private javax.swing.JToggleButton btnPaquete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDif;
    private javax.swing.JLabel lblPaq;
    private javax.swing.JLabel lblTot;
    private javax.swing.JTable tablePago;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtDif;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JComboBox<String> txtNombre;
    private javax.swing.JTextField txtPaq;
    // End of variables declaration//GEN-END:variables
}
